### ISSUE TITLE
If character sub 50 switches to shadowlands chromie time, APR shows not chromie time error

### ISSUE THREAD

**Issue by crazedVic** [Rycia/azeroth-pilot-reloaded#88]
there's 2 files that need to be updated:
QuestHandler.lua, line 978
Transport.lua, line 937

Guessing that with release of Dragonflight, Chromie time now allows Shadowlands pre-50.

hth

**Comment by Neogeekmo** [comment]
Can you give more context like Screenshot, APR version, what you have in the custom path, your class/race/lvl/faction at the time of the bug please

Because on my side having the Shadowland route with a lvl 10 character when I take the SL timeline at Chromie, I don't have any message telling me that I'm not in the right timeline

**Comment by Neogeekmo** [comment]
After having looked at the code I confirm that there is a issue with the lvl check that they are no longer required since the release of DF. 

I'll fix that, but consider providing more information for future tickets to make them easier to understand and fix.
