### ISSUE TITLE
Support for WowUp.io

### ISSUE THREAD

**Issue by lucala** [Rycia/azeroth-pilot-reloaded#9]
Would it be possible to attach the addon as a zip file to a release such that it can be grabbed by the _install from URL_ github link in the WowUp application? https://github.com/WowUp/WowUp/issues/1318

**Comment by CloudTekSystems** [comment]
Pretty sure Wago and Curse addons can't be combined (because curse won't give out API keys to devs that allow wago.io addons)

**Comment by lucala** [comment]
> Pretty sure Wago and Curse addons can't be combined (because curse won't give out API keys to devs that allow wago.io addons)

I don't know enough about this, but how was the original AAP able to be on curseforge and still loadable from WowUp?

**Comment by CloudTekSystems** [comment]
Curse used to provide wowup an api key, then they signed with wago.Io
(instead of curse) and curse rescinded their api key.--
Thanks,

-Derek Frobel  802-338-6371
Owner, CloudTek Systems

**Comment by Pahonix** [comment]
This has nothing to do with Wago. An addon can be on both Curseforge and Wago's Addons site at the same time. Prime Example:

https://addons.wago.io/addons/deadly-boss-mods-dbm
https://www.curseforge.com/wow/addons/deadly-boss-mods

Now that we're done with that.

I'll see what we can do about packaging up the addon so that WoWUp can see it. It's not something I have experience doing, but we'll look into it. I use WoWUp myself, but only for addons that aren't available via Curseforge (like ElvUI and things from WoWInterface), so I do have an affinity for it. Stay tuned.

**Comment by CloudTekSystems** [comment]
If the publisher post it at both sites, then ya, I think it’d be fine.

But wowup can’t get addons from curse anymore.
-- 
Thanks,

-Derek Frobel  802-338-6371
Owner, CloudTek Systems

**Comment by NightofStarrs** [comment]
This has been resolved with v1.6.2 that was uploaded to Github. This properly pushed the update to Curseforge and WoWInterface. At this time, you should also be able to install via the Addon URL, or with manual pushes to WoWInterface that will update on WowUp.


![](https://cdn.discordapp.com/attachments/969416833688035438/1043994968651481189/image.png)
